create_alarm:
  name: Crea sveglia Alexa
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: alexa_devices
    timestamp:
      required: true
      selector:
        datetime:
    recurrence:
      selector:
        select:
          options:
            - once
            - daily
create_timer:
  name: Crea timer Alexa
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: alexa_devices
    duration:
      required: true
      selector:
        duration:
    label:
      selector:
        text:
create_reminder:
  name: Crea promemoria Alexa
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: alexa_devices
    timestamp:
      required: true
      selector:
        datetime:
    label:
      required: true
      selector:
        text:
list_notifications:
  name: Elenca eventi Alexa
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: alexa_devices
delete_notification:
  name: Elimina evento Alexa
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: alexa_devices
    notification_id:
      required: true
      selector:
        text:
delete_next_notification:
  name: Elimina il prossimo evento Alexa
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: alexa_devices
    kind:
      required: true
      selector:
        select:
          options:
            - alarm
            - timer
            - reminder
