name: e-Face Asterisk
version: 0.1.0-dev
slug: e_asterisk
stage: experimental
boot: manual
startup: application
description: Asterisk con provisioning persistente degli interni e-Face
url: https://github.com/edmondoalex/e-Face-X4
arch:
  - amd64
  - aarch64
homeassistant_api: true
map:
  - addon_config:rw
  - media:rw
  - ssl
  - homeassistant_config:rw
options:
  ami_password: null
  auto_add: true
  auto_add_secret: ""
  video_support: false
  register_ingress_entry: true
  generate_ssl_cert: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  additional_sounds: []
  mailbox: false
  mailbox_port: 12345
  mailbox_password: ""
  mailbox_extension: "100"
  mailbox_google_api_key: ""
  log_level: info
  eface_provision_token: ""
schema:
  ami_password: password
  auto_add: bool
  auto_add_secret: password
  video_support: bool
  additional_sounds:
    - str
  register_ingress_entry: bool
  generate_ssl_cert: bool
  certfile: str
  keyfile: str
  mailbox: bool
  mailbox_port: port
  mailbox_password: password
  mailbox_extension: str
  mailbox_google_api_key: password
  log_level: list(all|trace|debug|info|notice|warning|error|fatal|off)
  eface_provision_token: password
host_network: true
init: false
uart: true
stdin: true
ingress: true
ingress_port: 8088
