"""Persistent, isolated PJSIP configuration owned by e-Face.

This is the storage core for the planned Asterisk-side provisioner. It does
not run inside the current third-party add-on and must not be used as-is on a
live installation.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import threading
from pathlib import Path
from typing import Callable

_LOCK = threading.RLock()
_USERNAME = re.compile(r"[a-z][a-z0-9_-]{2,31}\Z")
_PASSWORD = re.compile(r"[A-Za-z0-9_-]{20,128}\Z")


def _atomic_write(path: Path, data: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{secrets.token_hex(8)}.tmp")
    try:
        with temporary.open("x", encoding="utf-8", newline="\n") as file:
            os.chmod(temporary, 0o600)
            file.write(data)
            file.flush()
            os.fsync(file.fileno())
        temporary.replace(path)
        if os.name == "posix":
            directory_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
    finally:
        temporary.unlink(missing_ok=True)


def _validate(username: str, extension: str, password: str, name: str) -> str:
    if not _USERNAME.fullmatch(username):
        raise ValueError("Nome utente e-Face non valido")
    if not extension.isdigit() or len(extension) != 4 or not 8302 <= int(extension) <= 8399:
        raise ValueError("Interno SIP fuori dalla fascia e-Face")
    if not _PASSWORD.fullmatch(password):
        raise ValueError("Password SIP non valida")
    cleaned = "".join(char for char in name if char.isalnum() or char in " -_").strip()[:64]
    if not cleaned:
        raise ValueError("Nome visualizzato non valido")
    return cleaned


def render(records: dict[str, dict]) -> str:
    """Render only e-Face-owned endpoints, never existing DoorBird/Control4."""
    output = ["; Generated by e-Face. Do not edit manually.\n"]
    used: set[str] = set()
    for username, record in sorted(records.items()):
        extension = str(record["extension"])
        password = str(record["password"])
        name = _validate(username, extension, password, str(record["name"]))
        if extension in used:
            raise ValueError("Interno SIP duplicato")
        used.add(extension)
        output.append(
            f"\n[{extension}]\ntype=aor\nmax_contacts=1\nremove_existing=yes\nsupport_path=yes\n"
            f"\n[{extension}]\ntype=auth\nauth_type=userpass\nusername={extension}\npassword={password}\n"
            f"\n[{extension}]\ntype=endpoint\naors={extension}\nauth={extension}\n"
            f'callerid="{name}" <{extension}>\ncontext=eface-test\n'
            "webrtc=yes\nfrom_domain=asterisk\nrtp_symmetric=yes\nforce_rport=yes\n"
            "rewrite_contact=yes\ndirect_media=no\nallow=!all,opus,alaw,ulaw\n"
        )
    return "".join(output)


class ManagedConfig:
    def __init__(self, directory: Path) -> None:
        self.directory = directory
        self.state = directory / "phones.json"
        self.pjsip = directory / "pjsip.conf"
        self.state_backup = directory / "phones.json.bak"
        self.pjsip_backup = directory / "pjsip.conf.bak"
        self.pending = directory / "transaction.pending"

    def load(self) -> dict[str, dict]:
        try:
            value = json.loads(self.state.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return {}
        if not isinstance(value, dict):
            raise ValueError("Inventario SIP danneggiato")
        render(value)  # Validate before using a persistent record.
        return value

    def reconcile_file(self) -> None:
        """Recover interrupted writes, then repair generated config at startup."""
        with _LOCK:
            if self.pending.exists():
                if not self.state_backup.exists() or not self.pjsip_backup.exists():
                    raise RuntimeError("Backup SIP mancante durante il recupero")
                _atomic_write(self.state, self.state_backup.read_text(encoding="utf-8"))
                _atomic_write(self.pjsip, self.pjsip_backup.read_text(encoding="utf-8"))
                self.pending.unlink()
            expected = render(self.load())
            if not self.pjsip.exists() or self.pjsip.read_text(encoding="utf-8") != expected:
                _atomic_write(self.pjsip, expected)

    def upsert(
        self,
        username: str,
        extension: str,
        password: str,
        name: str,
        reload_pjsip: Callable[[], None],
        endpoint_exists: Callable[[str], bool],
    ) -> None:
        _validate(username, extension, password, name)
        with _LOCK:
            previous = self.load()
            for owner, value in previous.items():
                if owner != username and value["extension"] == extension:
                    raise ValueError("Interno SIP già assegnato")
            if username not in previous and endpoint_exists(extension):
                raise ValueError("Interno SIP già presente fuori da e-Face")
            updated = {**previous, username: {"extension": extension, "password": password, "name": name}}
            generated = render(updated)
            if updated == previous:
                self.reconcile_file()
                if not endpoint_exists(extension):
                    reload_pjsip()
                    if not endpoint_exists(extension):
                        raise RuntimeError("Asterisk non vede l'interno già configurato")
                return
            previous_state = json.dumps(previous, ensure_ascii=False, sort_keys=True)
            previous_conf = render(previous)
            _atomic_write(self.state_backup, previous_state)
            _atomic_write(self.pjsip_backup, previous_conf)
            _atomic_write(self.pending, "pending\n")
            try:
                _atomic_write(self.state, json.dumps(updated, ensure_ascii=False, sort_keys=True))
                _atomic_write(self.pjsip, generated)
                reload_pjsip()
                if not endpoint_exists(extension):
                    raise RuntimeError("Asterisk non vede il nuovo interno")
                self.pending.unlink()
            except Exception:
                _atomic_write(self.state, previous_state)
                _atomic_write(self.pjsip, previous_conf)
                try:
                    reload_pjsip()
                except Exception:
                    pass  # Keep the pending marker: next startup restores files.
                else:
                    self.pending.unlink()
                raise

    def revoke(
        self,
        username: str,
        reload_pjsip: Callable[[], None],
        endpoint_exists: Callable[[str], bool],
    ) -> bool:
        """Remove only a managed phone; restore it if Asterisk still sees it."""
        with _LOCK:
            previous = self.load()
            if username not in previous:
                return False
            extension = str(previous[username]["extension"])
            updated = {name: record for name, record in previous.items() if name != username}
            previous_state = json.dumps(previous, ensure_ascii=False, sort_keys=True)
            previous_conf = render(previous)
            _atomic_write(self.state_backup, previous_state)
            _atomic_write(self.pjsip_backup, previous_conf)
            _atomic_write(self.pending, "pending\n")
            try:
                _atomic_write(self.state, json.dumps(updated, ensure_ascii=False, sort_keys=True))
                _atomic_write(self.pjsip, render(updated))
                reload_pjsip()
                if endpoint_exists(extension):
                    raise RuntimeError("Asterisk vede ancora l'interno revocato")
                self.pending.unlink()
                return True
            except Exception:
                _atomic_write(self.state, previous_state)
                _atomic_write(self.pjsip, previous_conf)
                try:
                    reload_pjsip()
                except Exception:
                    pass
                else:
                    self.pending.unlink()
                raise
